// modules/clawhub-adapter.js - ClawHub 技能市场适配器
// 搜索/下载/转换 OpenClaw ClawHub 技能为本地 skill.json 格式
'use strict';

var Core = null;
var fs = null;
var path = null;
var https = null;

var CLAWHUB_API = 'https://api.clawhub.ai/v1';
var INSTALLED_FILE = '_clawhub_installed.json';

function getInstalledPath() {
  return path.join(Core.DATA_ROOT, 'skills', INSTALLED_FILE);
}

function loadInstalled() {
  try {
    var p = getInstalledPath();
    if (fs.existsSync(p)) return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch (e) { console.warn('⚠️ [clawhub-adapter] 操作失败:', e.message || e); }
  return { skills: [], lastSync: null };
}

function saveInstalled(data) {
  try {
    var dir = path.join(Core.DATA_ROOT, 'skills');
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(getInstalledPath(), JSON.stringify(data, null, 2), 'utf8');
  } catch (e) { console.warn('⚠️ [clawhub-adapter] 操作失败:', e.message || e); }
}

// ===== HTTP 请求工具 =====
function httpGet(url) {
  return new Promise(function(resolve, reject) {
    if (!https) { try { https = require('https'); } catch(e) { reject(e); return; } }
    var req = https.get(url, { headers: { 'User-Agent': 'AIAgentPro/1.0', 'Accept': 'application/json' }, timeout: 15000 }, function(res) {
      var body = '';
      res.on('data', function(c) { body += c; });
      res.on('end', function() {
        try { resolve(JSON.parse(body)); } catch(e) { resolve(body); }
      });
    });
    req.on('error', reject);
    req.on('timeout', function() { req.destroy(); reject(new Error('timeout')); });
  });
}

// ===== 搜索 ClawHub 技能 =====
async function searchSkills(query, limit) {
  limit = limit || 10;
  try {
    var url = CLAWHUB_API + '/skills/search?q=' + encodeURIComponent(query) + '&limit=' + limit;
    var data = await httpGet(url);
    if (data && data.skills) return data.skills;
    if (data && data.results) return data.results;
    if (Array.isArray(data)) return data;
    return [];
  } catch(e) {
    console.warn('[clawhub] 搜索失败:', e.message);
    return [];
  }
}

// ===== 获取技能详情 =====
async function getSkillDetail(skillId) {
  try {
    var url = CLAWHUB_API + '/skills/' + encodeURIComponent(skillId);
    return await httpGet(url);
  } catch(e) {
    return null;
  }
}

// ===== 下载并转换技能 =====
async function installSkill(skillId) {
  var detail = await getSkillDetail(skillId);
  if (!detail) return { success: false, error: '技能不存在或网络错误' };

  // 转换为本地格式
  var localSkill = convertToLocalFormat(detail);
  if (!localSkill) return { success: false, error: '格式转换失败' };

  // 写入 skills 目录
  var skillDir = path.join(Core.DATA_ROOT, 'skills', localSkill.id);
  try {
    if (!fs.existsSync(skillDir)) fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(path.join(skillDir, 'skill.json'), JSON.stringify(localSkill.json, null, 2), 'utf8');
    fs.writeFileSync(path.join(skillDir, 'prompt.md'), localSkill.prompt, 'utf8');

    // 记录安装
    var installed = loadInstalled();
    installed.skills.push({ id: localSkill.id, clawhubId: skillId, name: localSkill.json.name, installedAt: new Date().toISOString() });
    installed.lastSync = new Date().toISOString();
    saveInstalled(installed);

    console.log('[clawhub] 技能已安装: ' + localSkill.json.name);
    return { success: true, id: localSkill.id, name: localSkill.json.name };
  } catch(e) {
    return { success: false, error: e.message };
  }
}

// ===== 格式转换：OpenClaw Skill → 本地 skill.json + prompt.md =====
function convertToLocalFormat(ocSkill) {
  try {
    var name = ocSkill.name || ocSkill.title || ocSkill.id || 'unknown';
    var desc = ocSkill.description || ocSkill.summary || '';
    var prompt = ocSkill.prompt || ocSkill.content || ocSkill.instructions || '';
    var tools = ocSkill.tools || ocSkill.required_tools || [];

    // 如果是 YAML manifest 格式，尝试提取
    if (ocSkill.manifest) {
      var m = ocSkill.manifest;
      name = m.name || name;
      desc = m.description || desc;
      prompt = m.prompt || m.instructions || prompt;
      tools = m.tools || tools;
    }

    var localId = 'clawhub_' + name.replace(/[^a-zA-Z0-9\u4e00-\u9fa5]/g, '_').substring(0, 40);

    return {
      id: localId,
      json: {
        id: localId,
        name: name.substring(0, 40),
        description: desc.substring(0, 200),
        version: ocSkill.version || '1.0.0',
        source: 'clawhub',
        clawhubId: ocSkill.id || ocSkill.skill_id || '',
        tools_required: tools,
        autoGenerated: true,
        installedAt: new Date().toISOString()
      },
      prompt: '# ' + name + '\n\n' + (desc ? '> ' + desc + '\n\n' : '') + prompt + '\n'
    };
  } catch(e) {
    return null;
  }
}

// ===== 列出已安装的 ClawHub 技能 =====
function listInstalled() {
  return loadInstalled().skills || [];
}

// ===== 卸载 =====
function uninstallSkill(localId) {
  var skillDir = path.join(Core.DATA_ROOT, 'skills', localId);
  try {
    if (fs.existsSync(skillDir)) {
      fs.rmSync(skillDir, { recursive: true, force: true });
    }
    var installed = loadInstalled();
    installed.skills = installed.skills.filter(function(s) { return s.id !== localId; });
    saveInstalled(installed);
    return { success: true };
  } catch(e) {
    return { success: false, error: e.message };
  }
}

// ===== 命令 =====
function registerCommands() {
  if (!Core.custom || !Core.custom.registerCommand) return;

  Core.custom.registerCommand('clawhub', {
    zh: 'ClawHub技能市场: /clawhub search|install|list|remove',
    en: 'ClawHub skill marketplace'
  }, function(args) {
    var parts = (args || '').trim().split(/\s+/);
    var sub = parts[0] || 'list';

    if (sub === 'search') {
      var query = parts.slice(1).join(' ');
      if (!query) { showMsg('用法: /clawhub search <关键词>'); return; }
      showMsg('正在搜索 ClawHub: "' + query + '"...');
      searchSkills(query, 8).then(function(results) {
        if (!results || results.length === 0) { showMsg('未找到相关技能'); return; }
        var text = '🔍 **ClawHub 搜索结果** ("' + query + '")\n\n';
        results.forEach(function(s, i) {
          var name = s.name || s.title || s.id;
          var desc = (s.description || s.summary || '').substring(0, 60);
          var id = s.id || s.skill_id || '';
          text += (i+1) + '. **' + name + '**\n   ' + desc + '\n   安装: /clawhub install ' + id + '\n\n';
        });
        showMsg(text);
      });
      return;
    }

    if (sub === 'install') {
      var skillId = parts[1] || '';
      if (!skillId) { showMsg('用法: /clawhub install <skill_id>'); return; }
      showMsg('正在安装: ' + skillId + '...');
      installSkill(skillId).then(function(r) {
        if (r.success) showMsg('✅ 已安装: ' + r.name + '\n技能ID: ' + r.id + '\n\n在技能列表中激活即可使用。');
        else showMsg('❌ 安装失败: ' + r.error);
      });
      return;
    }

    if (sub === 'list') {
      var installed = listInstalled();
      if (installed.length === 0) { showMsg('暂无已安装的 ClawHub 技能。\n\n搜索: /clawhub search <关键词>\n安装: /clawhub install <id>'); return; }
      var text = '📦 **已安装 ClawHub 技能** (' + installed.length + ')\n\n';
      installed.forEach(function(s, i) {
        text += (i+1) + '. ' + s.name + ' (ID: ' + s.id + ')\n';
      });
      text += '\n卸载: /clawhub remove <id>';
      showMsg(text);
      return;
    }

    if (sub === 'remove') {
      var id = parts[1] || '';
      if (!id) { showMsg('用法: /clawhub remove <skill_id>'); return; }
      var r = uninstallSkill(id);
      showMsg(r.success ? '✅ 已卸载' : '❌ ' + r.error);
      return;
    }

    showMsg('📦 ClawHub 技能市场:\n/clawhub search <关键词> — 搜索技能\n/clawhub install <id> — 安装技能\n/clawhub list — 已安装列表\n/clawhub remove <id> — 卸载');
  });
}

function showMsg(text) {
  var id = Core.session.getCurrentId();
  if (id && Core.session.addMessage) {
    Core.session.addMessage(text, 'assistant');
    if (Core.session.renderMessages) Core.session.renderMessages(id);
  }
}

// ===== 初始化 =====
function init(_Core) {
  Core = _Core;
  try { fs = require('fs'); path = require('path'); https = require('https'); } catch(e) { return; }

  registerCommands();

  Core.clawhub = {
    search: searchSkills,
    install: installSkill,
    uninstall: uninstallSkill,
    listInstalled: listInstalled,
    convertToLocalFormat: convertToLocalFormat
  };

  var count = listInstalled().length;
  console.log('✅ clawhub-adapter.js 已加载 | 已安装技能: ' + count);
}

module.exports = { name: 'clawhub-adapter', dependencies: ['custom', 'session', 'skill'], init: init };
