// modules/pipeline-ppt.js - PPT 生成管线模块
// 从大纲/主题自动生成 PowerPoint 演示文稿
const fs = require('fs');
const path = require('path');
const pptxgen = require('pptxgenjs');

let Core = null;

const THEME = {
  bg: '1a1a2e',
  text: 'FFFFFF',
  accent: '4a9eff',
  titleSize: 36,
  bulletSize: 18,
  noteSize: 12
};

function getOutputDir() {
  if (Core.deliverables && Core.deliverables.getOutputDir) {
    return Core.deliverables.getOutputDir('ppt');
  }
  const dir = path.join(Core.DATA_ROOT, 'deliverables', 'ppt');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function registerDeliverable(filePath, title) {
  if (Core.deliverables && Core.deliverables.register) {
    Core.deliverables.register({ type: 'ppt', filePath, title });
  }
}

function sanitizeFilename(name) {
  return name.replace(/[<>:"/\|?*]/g, '_').slice(0, 80);
}

// ═══════════════════════════════════════════
// generate - 从结构化数据生成 PPT
// ═══════════════════════════════════════════
async function generate(options) {
  const { title, slides, theme, outputPath } = options || {};
  if (!title || !slides || !slides.length) {
    return { success: false, error: 'title and slides[] are required' };
  }

  const t = Object.assign({}, THEME, theme || {});
  const pres = new pptxgen();
  pres.defineLayout({ name: 'CUSTOM', width: 10, height: 7.5 });
  pres.layout = 'CUSTOM';

  // Title slide
  const titleSlide = pres.addSlide();
  titleSlide.background = { color: t.bg };
  titleSlide.addText(title, {
    x: 0.8, y: 2.5, w: 8.4, h: 1.5,
    fontSize: t.titleSize, color: t.text, bold: true, align: 'center'
  });
  titleSlide.addText('Generated by pipeline-ppt', {
    x: 0.8, y: 4.2, w: 8.4, h: 0.5,
    fontSize: 12, color: t.accent, align: 'center'
  });

  // Content slides
  for (const s of slides) {
    const slide = pres.addSlide();
    slide.background = { color: t.bg };
    slide.addText(s.title || '', {
      x: 0.6, y: 0.4, w: 8.8, h: 0.8,
      fontSize: 26, color: t.accent, bold: true
    });
    if (s.bullets && s.bullets.length) {
      const bulletText = s.bullets.map(b => ({ text: b, options: { bullet: true, breakLine: true } }));
      slide.addText(bulletText, {
        x: 0.8, y: 1.5, w: 8.4, h: 5.2,
        fontSize: t.bulletSize, color: t.text, valign: 'top', paraSpaceAfter: 8
      });
    }
    if (s.notes) {
      slide.addNotes(s.notes);
    }
  }

  const outDir = getOutputDir();
  const fileName = sanitizeFilename(title) + '.pptx';
  const filePath = outputPath || path.join(outDir, fileName);
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  await pres.writeFile({ fileName: filePath });
  registerDeliverable(filePath, title);

  return { success: true, filePath, slideCount: slides.length + 1 };
}

// ═══════════════════════════════════════════
// fromOutline - 从文本大纲生成 PPT
// ═══════════════════════════════════════════
async function fromOutline(title, outlineText) {
  if (!title || !outlineText) {
    return { success: false, error: 'title and outlineText are required' };
  }

  const lines = outlineText.split(/\r?\n/);
  const slides = [];
  let current = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (trimmed.startsWith('#')) {
      current = { title: trimmed.replace(/^#+\s*/, ''), bullets: [] };
      slides.push(current);
    } else if (trimmed.startsWith('-')) {
      const bullet = trimmed.replace(/^-\s*/, '');
      if (current) current.bullets.push(bullet);
      else { current = { title: title, bullets: [bullet] }; slides.push(current); }
    } else {
      if (current) current.bullets.push(trimmed);
      else { current = { title: trimmed, bullets: [] }; slides.push(current); }
    }
  }

  if (!slides.length) {
    return { success: false, error: 'No slides parsed from outline' };
  }

  const result = await generate({ title, slides });
  return { success: result.success, filePath: result.filePath, slideCount: result.slideCount };
}

// ═══════════════════════════════════════════
// fromTopic - 从主题自动生成 PPT
// ═══════════════════════════════════════════
async function fromTopic(topic) {
  if (!topic) return { success: false, error: 'topic is required' };
  if (!Core.api || !Core.api.callAPI) {
    return { success: false, error: 'Core.api.callAPI not available' };
  }

  const systemPrompt = 'You are a presentation outline generator. Given a topic, produce a structured outline. ' +
    'Use "# Slide Title" for each slide heading and "- bullet point" for content. ' +
    'Generate 5-8 slides. Output ONLY the outline, no extra commentary.';

  let outlineText;
  try {
    outlineText = await Core.api.callAPI(
      'Create a presentation outline about: ' + topic,
      systemPrompt, 0.7, null, null
    );
  } catch (e) {
    return { success: false, error: 'API call failed: ' + e.message };
  }

  if (!outlineText || typeof outlineText !== 'string') {
    return { success: false, error: 'Empty response from API' };
  }

  return fromOutline(topic, outlineText);
}

// ═══════════════════════════════════════════
// Module init
// ═══════════════════════════════════════════
function init(_Core) {
  Core = _Core;
  Core.pipelinePpt = { generate, fromOutline, fromTopic };
  console.log('[pipeline-ppt] initialized');
}

module.exports = { name: 'pipeline-ppt', dependencies: [], init };
